AppMalbec/urls.py
from django.urls import path
from AppMalbec.views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("", inicio, name= "Inicio"),
    path("usuarios/", UsuarioLista.as_view(), name="Usuarios"),
    path("usuarios/nuevo/", UsuarioCrear.as_view(), name= "UsuarioNuevo"),
    path("bazar/",BazarLista.as_view(), name="Bazar"),
    path("bazar/agregar/", BazarCrear.as_view(), name="AgregarBazar"),
    path("variedades/", VariedadesLista.as_view(), name="Variedades"),
    path("variedades/agregar/", VariedadAgregar.as_view(), name ="AgregarVariedad"),
    path("usuarios/<int:pk>/", UsuarioDetalle.as_view(), name ="DetalleUsuario"),
    path("bazar/<int:pk>/", BazarDetalle.as_view(), name= "BazarDetalles"),
    path("variedades/<int:pk>/", VariedadDetalle.as_view(), name= "DetalleVariedad"),
    path("usuarios/editar/<int:pk>/", UsuarioEditar.as_view(), name ="EditarUsuario"),
    path("bazar/editar/<int:pk>/", BazarEditar.as_view(), name= "EditarBazar"),
    path("variedades/editar/<int:pk>/", VariedadEditar.as_view(), name= "EditarVariedad"),
    path("usuarios/borrar/<int:pk>/", UsuarioBorrar.as_view(), name ="BorrarUsuario"),
    path("bazar/borrar/<int:pk>/", BazarBorrar.as_view(), name= "BorrarBazar"),
    path("variedades/borrar/<int:pk>/", VariedadBorrar.as_view(), name= "VariedadBorrar"),
    path("login/", inicio_sesion, name= "Login"),
    path("registro/", registro, name= "Registarse"), 
    path("sobre_mi/", SobreMi, name= "SobreMi" ),
    path("logout/", LogoutView.as_view(template_name="AppMalbec/logout.html"), name="Logout"),
    path("editarPerfil/", editarUsuario, name= "EditarPerfil"),
    path("nuevoAvatar/", agregarAvatar, name= "Avatar"),
]

MalbecVinos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path ("AppMalbec/", include("AppMalbec.urls")),
]

urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppMalbec/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Usuario(models.Model):
    nombre= models.CharField(max_length=50)
    apellido= models.CharField(max_length=50)
    email= models.EmailField()

class Variedad(models.Model):
    categoria= models.CharField(max_length=60)
    marca= models.CharField(max_length=60)
    precio= models.IntegerField()
    familia= models.CharField(max_length=50)
    imagen = models.ImageField(upload_to="bebidas", null=True, blank= True)

class Bazar(models.Model):
    tipo_de_producto = models.CharField(max_length=50)
    precio= models.IntegerField()
    imagen = models.ImageField(upload_to="bazar", null=True,blank= True)

class Avatar(models.Model):
    usuario= models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null= True, blank= True)

AppMalbec/forms.py
from django import forms
from django.contrib.auth.forms import  UserCreationForm
from django.contrib.auth.models import User
from AppMalbec.models import Avatar

class UsuarioRegistro(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label = "Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label = "Repetir la contraseña", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username", "email","first_name", "last_name", "password1", "password2"]


class FormEditar(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label = "Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label = "Repetir la contraseña", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["email","first_name", "last_name", "password1", "password2"]

class AvatarForm(forms.ModelForm):
    class Meta:
        model = Avatar
        fields =["imagen"]

AppMalbec/views.py
import re
from tkinter.tix import Form
from django.shortcuts import render
from AppMalbec.models import *
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, authenticate
from AppMalbec.forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


def inicio(request):
    return render(request, "AppMalbec/inicio.html")

def usuario(request):
    
    return render(request, "AppMalbec/usuario.html")

def bazar(request):
    return render(request, "AppMalbec/bazar.html")

def variedades(request):
    bebidas= Variedad.objects.filter()
    contexto= {"url":bebidas.imagen.url}

    return render(request, "AppMalbec/variedad.html", contexto)  

def SobreMi(request):
    return render(request, "AppMalbec/SobreMi.html")

def inicio_sesion(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data = request.POST)

        if form.is_valid():
            usuario = form.cleaned_data.get("username")
            contra = form.cleaned_data.get("password")

            user = authenticate(username= usuario, password= contra)

            if user:
                login(request, user)
                return render(request, "AppMalbec/inicio.html", { "mensaje": f"Bienvenido {user}"})

        else:
            return render(request, "AppMalbec/inicio.html", {"mensaje": "Datos incorrectos."})

    else: 
        form = AuthenticationForm() 
    return render(request, "AppMalbec/login.html", {"formulario": form})

def registro(request):
    if request.method == "POST":
        form = UsuarioRegistro(request.POST)

        if form.is_valid():
            username= form.cleaned_data["username"]
            form.save()
            return render(request, "AppMalbec/inicio.html", {"mensaje": "Usuario creado."})
    else:
        form = UsuarioRegistro()  
    return render(request, "AppMalbec/registro.html", {"formulario":form})   


@login_required
def editarUsuario(request):

    usuario = request.user

    if request.method == "POST":
        form = FormEditar(request.POST)

        if form.is_valid():

            info = form.cleaned_data

            usuario.email = info["email"]
            usuario.set_password(info["password1"])
            usuario.first_name = info["first_name"]
            usuario.last_name = info ["last_name"]

            usuario.save()

            return render(request, "AppMalbec/inicio.html")
    else:
        form = FormEditar(initial={
            "email":usuario.email,
            "first_name":usuario.first_name,
            "last_name":usuario.last_name,
        })
    return render(request, "AppMalbec/editarPerfil.html", {"formulario":form, "usuario":usuario})

@login_required
def agregarAvatar(request):

    if request.method == "POST":
        form = AvatarForm(request.POST, request.FILES)

        if form.is_valid():
            usuarioNuevo = User.objects.get(username=request.user)
            avatar = Avatar(usuario=usuarioNuevo, imagen=form.cleaned_data["imagen"])
            avatar.save()

            return render(request,"AppMalbec/inicio.html")
    else:
        form= AvatarForm()

    return render(request, "AppMalbec/nuevoAvatar.html", {"formulario":form})

# Create your views here.

class UsuarioLista(LoginRequiredMixin,ListView):
    model = Usuario
    template_name = "AppMalbec/usuario.html"

class UsuarioCrear(LoginRequiredMixin,CreateView):
    model = Usuario
    success_url = "/AppMalbec/usuarios/"
    fields = ["nombre", "apellido", "email"]

class UsuarioDetalle(LoginRequiredMixin,DetailView):
    model= Usuario

class UsuarioEditar(LoginRequiredMixin,UpdateView):
    model= Usuario
    success_url = "/AppMalbec/usuarios/"
    fields = ["nombre", "apellido", "email"]

class UsuarioBorrar(LoginRequiredMixin,DeleteView):
    model= Usuario
    success_url = "/AppMalbec/usuarios/"

class BazarLista(LoginRequiredMixin,ListView):
    model = Bazar
    template_name = "AppMalbec/bazar.html"
    
class BazarCrear(LoginRequiredMixin,CreateView):
    model= Bazar
    success_url = "/AppMalbec/bazar/"
    fields = ["tipo_de_producto", "precio", "imagen"]

class BazarDetalle(LoginRequiredMixin,DetailView):
    model= Bazar

class BazarEditar(LoginRequiredMixin,UpdateView):
    model= Bazar
    success_url = "/AppMalbec/bazar/"
    fields = ["tipo_de_producto", "precio","imagen"]

class BazarBorrar(LoginRequiredMixin,DeleteView):
    model= Bazar
    success_url = "/AppMalbec/bazar/"

class VariedadesLista(LoginRequiredMixin,ListView):
    model = Variedad
    template_name = "AppMalbec/variedad.html"

class VariedadAgregar(LoginRequiredMixin,CreateView):
    model = Variedad
    success_url = "/AppMalbec/variedades/"
    fields = ["categoria", "marca", "precio", "familia", "imagen"]

class VariedadDetalle(LoginRequiredMixin,DetailView):
    model= Variedad

class VariedadEditar(LoginRequiredMixin,UpdateView):
    model = Variedad
    success_url = "/AppMalbec/variedades/"
    fields = ["categoria", "marca", "precio", "familia", "imagen"]

class VariedadBorrar(LoginRequiredMixin,DeleteView):
    model = Variedad
    success_url = "/AppMalbec/variedades/"

AppMalbec/templates/AppMalbec/bazar.html
{% extends "AppMalbec/padre.html" %}

{% load static %}

{% block titulo %}

CRISTALERÍA, DECANTADORES Y SACACORCHOS
                                
{% endblock %}

{% block pie%}
<h2>Bazar</h2>

{% for bazar in object_list %}
<ul><li>
   {{bazar.tipo_de_producto}} <br> Precio: {{bazar.precio}}
</li>
</ul> 
<a href="{% url 'BazarDetalles' bazar.id %}">Ver Detalles</a>
<a href="{% url 'EditarBazar' bazar.id %}">Actualizar Bazar</a>
<a href="{% url 'BorrarBazar' bazar.id %}">Borrar</a>
{% endfor %}<br>
<a href="{% url 'AgregarBazar' %}">Agregar Nuevo Bazar</a>
                                
{% endblock %}

AppMalbec/templates/AppMalbec/bazar_confirm_delete.html
{% extends "AppMalbec/padre.html" %}



{% block titulo %}

Detalles del Bazar

{% endblock %}

{% block pie%}
<form action="" method="POST"enctype="multipart/form-data"> {% csrf_token %}

    <p>Borrar {{bazar.tipo_de_producto}} ? </p>
    <input type="submit" value="Aceptar">
</form>

{% endblock %}

AppMalbec/templates/AppMalbec/bazar_detail.html
{% extends "AppMalbec/padre.html" %}



{% block titulo %}

Detalles del Bazar

{% endblock %}

{% block pie%}
<p>{{bazar.tipo_de_producto}} </p>
 <br>
<p>Precio:{{bazar.precio}}</p>
               

{% endblock %}

AppMalbec/templates/AppMalbec/inicio.html
{% extends "AppMalbec/padre.html" %}

{% load static %}

{% block titulo %}

<h1 style="color:black">MALBEC</h1>
<h2>Tienda de vinos</h2>

<h1>{{mensaje}}</h1>
 
                                
{% endblock %}

AppMalbec/templates/AppMalbec/nuevoAvatar.html
{% extends "AppMalbec/padre.html" %}

{% load static %}

{% block titulo %}

<h1 style="color:black"> Crear Avatar </h1>

<form action="" method="POST"enctype="multipart/form-data">{% csrf_token %}

    {{formulario.as_p}}
    
    <button type="submit">Crear</button>
    
    </form>

                             
{% endblock %}

AppMalbec/templates/AppMalbec/registro.html
{% extends "AppMalbec/padre.html" %}

{% load static %}

{% block titulo %}

<h1 style="color:black"> Crear Usuario </h1>

<form action="" method="POST">{% csrf_token %}

    {{formulario.as_p}} 
    
    <button class="btn btn-primary" type="submit" >Registrarse</button>
    
    </form>
                        
{% endblock %}

AppMalbec/templates/AppMalbec/usuario.html
{% extends "AppMalbec/padre.html" %}

{% load static %}

{% block titulo %}

CLIENTES
                                
{% endblock %}

{% block pie%}

<h1>Usuario</h1>

{% for usuario in object_list %}

<ul><li>Nombre: {{usuario.nombre}} {{usuario.apellido}} </li>
<li>Email: {{usuario.email}}</li>
</ul>
<a href="{% url 'DetalleUsuario' usuario.id %} ">Ver Detalles</a>
<a href="{% url 'EditarUsuario' usuario.id %} ">Editar</a>
<a href="{% url 'BorrarUsuario' usuario.id %} ">Borrar</a>
{% endfor %}<br>

<a href="{% url 'UsuarioNuevo' %}">Crear Nuevo Usuario</a>
                                
{% endblock %}

AppMalbec/templates/AppMalbec/usuario_confirm_delete.html
{% extends "AppMalbec/padre.html" %}



{% block titulo %}

Detalles del Usuario  

{% endblock %}

{% block pie%}

<form action="" method="POST"> {% csrf_token %}

    <p>Borrar {{usuario.nombre}} {{usuario.apellido}} ? </p>
    <input type="submit" value="Aceptar">
</form>

{% endblock %}

AppMalbec/templates/AppMalbec/usuario_detail.html
{% extends "AppMalbec/padre.html" %}



{% block titulo %}

Detalles del Usuario  

{% endblock %}

{% block pie%}

<p>Nombre: {{usuario.nombre}} {{usuario.apellido}} </p>   <br>
<p>Email: {{usuario.email}}</p>

{% endblock %}

AppMalbec/templates/AppMalbec/usuario_form.html
{% extends "AppMalbec/padre.html" %}



{% block titulo %}

Crear nuevo usuario  

{% endblock %}

{% block pie%}

<form action="" method="POST">{% csrf_token %}
    <table>
        {{form.as_p}}
    </table>

<input type="submit" value="Enviar">

</form>                 

{% endblock %}

AppMalbec/templates/AppMalbec/variedad.html
{% extends "AppMalbec/padre.html" %}

{% load static %}

{% block titulo %}

VARIEDADES
                                
{% endblock %}

{% block pie%}
<h1>Bebidas</h1>
{% for variedad in object_list %}

<ul>
    <li>
        {{variedad.categoria}} <br> {{variedad.marca}} {{variedad.familia}} <br> Precio: {{variedad.precio}} <br>
        
        {% with user.variedad_set.first as bebida %}
                <img src="p.imagen.url" alt="No hay imagen" style="max-width: 75px ;" enctype="multipart/form-data">
                {% endwith %}
    </li>
</ul>
<a href="{% url 'DetalleVariedad' variedad.id %} ">Ver Detalles</a>
<a href="{% url 'EditarVariedad' variedad.id %} ">Actualizar Datos</a> 
<a href="{% url 'VariedadBorrar' variedad.id %} ">Borrar</a>

{% endfor %}<br>
<a href="{% url 'AgregarVariedad' %}">Agregar Nueva Bebida</a>
{% endblock %}

AppMalbec/templates/AppMalbec/variedad_confirm_delete.html
{% extends "AppMalbec/padre.html" %}


{% block titulo %}

Detalles de las Bebidas

{% endblock %}

{% block pie%}

<form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}

    <p>Borrar {{variedad.marca}} {{variedad.familia}} ? </p>
    <input type="submit" value="Aceptar">
</form>
{% endblock %}

AppMalbec/templates/AppMalbec/variedad_detail.html
{% extends "AppMalbec/padre.html" %}


{% block titulo %}

Detalles de las Bebidas

{% endblock %}

{% block pie%}

<p>{{variedad.categoria}} <br> {{variedad.marca}} {{variedad.familia}}</p>  
 <br> 
<p>Precio: {{variedad.precio}}</p>  

{% endblock %}

AppMalbec/templates/AppMalbec/variedad_form.html
{% extends "AppMalbec/padre.html" %}


{% block titulo %}

Agregar Bebidas

{% endblock %}

{% block pie%}

<form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <table>
        {{form.as_p}}
    </table>



<input type="submit" value="Enviar">

</form>                 

{% endblock %}